# Navigate to server directory first
cd server

# Install server dependencies
npm install express@4.18.2
npm install mongoose@7.0.5
npm install bcrypt@5.1.0
npm install body-parser@1.20.2
npm install cors@2.8.5
npm install dotenv@16.0.3
npm install jsonwebtoken@9.0.0
npm install multer@1.4.5-lts.1
npm install nodemon@2.0.22



# Navigate to client directory
cd client

# Install client dependencies
npm install @emotion/react@11.10.6
npm install @emotion/styled@11.10.6
npm install @mantine/modals@6.0.9
npm install @mui/icons-material@5.11.16
npm install @mui/material@5.11.16
npm install @testing-library/jest-dom@5.16.5
npm install @testing-library/react@13.4.0
npm install @testing-library/user-event@13.5.0
npm install axios@1.4.0
npm install react@18.2.0
npm install react-dom@18.2.0
npm install react-redux@8.0.5
npm install react-router-dom@6.11.1
npm install react-scripts@5.0.1
npm install redux@4.2.1
npm install redux-thunk@2.4.2
npm install web-vitals@2.1.4





# Server dev dependencies
cd server
npm install -D nodemon

# Client dev dependencies
cd client
npm install -D @types/react
npm install -D @types/react-dom

Important Notes:
    Make sure you have Node.js and npm installed first. Check with:
node --version
npm --version




For Server (.env):
    PORT=5000
    MONGO_DB=your_mongodb_connection_string
    JWT_KEY=your_jwt_secret


For Client (.env):
    REACT_APP_PUBLIC_FOLDER=http://localhost:5000/images/

After installation, verify your package.json files:
        Server package.json should include:

            {
  "dependencies": {
    "bcrypt": "^5.1.0",
    "body-parser": "^1.20.2",
    "cors": "^2.8.5",
    "dotenv": "^16.0.3",
    "express": "^4.18.2",
    "jsonwebtoken": "^9.0.0",
    "mongoose": "^7.0.5",
    "multer": "^1.4.5-lts.1",
    "nodemon": "^2.0.22"
  }
}


Client package.json should include:
{
  "dependencies": {
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@mantine/modals": "^6.0.9",
    "@mui/icons-material": "^5.11.16",
    "@mui/material": "^5.11.16",
    "@testing-library/jest-dom": "^5.16.5",
    "@testing-library/react": "^13.4.0",
    "@testing-library/user-event": "^13.5.0",
    "axios": "^1.4.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-redux": "^8.0.5",
    "react-router-dom": "^6.11.1",
    "react-scripts": "5.0.1",
    "redux": "^4.2.1",
    "redux-thunk": "^2.4.2",
    "web-vitals": "^2.1.4"
  }
}